### ISSUE TITLE
Useless error handling

### ISSUE THREAD

**Issue by GorgeousPuree** [dpgolang/PetBook#22]
https://github.com/dpgolang/PetBook/blob/40feba1db839279ac993ca5409134199f5df3b3e/pkg/controllers/search.go#L35

There are a lot of useless 'if err != nil' checks like at 35 line. Please notice that logger.Error(err) simply adds error description in .log file and outputs this error in terminal. In other words, those checks do nothing. If a real error happens, your handlers will not prevent error exceptions. Add returns, redirects in your 'if err != nil' statements.

**Comment by alyonaprylypa** [comment]
Done
